== copyright-statement
=== {blank}
[[copyright]]
[align="left"]
Copyright © {{ docyear }} by The Institute of Electrical and Electronics Engineers, Inc. +
Three Park Avenue +
New York, New York 10016-5997, USA

All rights reserved.

== license-statement
=== {blank}
This document is an unapproved draft of a proposed IEEE Standard. As such, this document is subject to change. USE AT YOUR OWN RISK! IEEE copyright statements SHALL NOT BE REMOVED from draft or approved IEEE standards, or modified in any way. Because this is an unapproved draft, this document must not be utilized for any conformance/compliance purposes. Permission is hereby granted for officers from each IEEE Standards Working Group or Committee to reproduce the draft document developed by that Working Group for purposes of international standardization consideration.  IEEE Standards Department must be informed of the submission for consideration prior to any reproduction for international standardization consideration (stds-ipr@ieee.org). Prior to adoption of this document, in whole or in part, by another standards development organization, permission must first be obtained from the IEEE Standards Department (stds-ipr@ieee.org). When requesting permission, IEEE Standards Department will require a copy of the standard development organization's document highlighting the use of IEEE content. Other entities seeking permission to reproduce this document, in whole or in part, must also obtain permission from the IEEE Standards Department.

[align="left"]
IEEE Standards Department +
445 Hoes Lane +
Piscataway, NJ 08854, USA

== legal-statement
[[boilerplate-disclaimers]]
=== Important Notices and Disclaimers Concerning IEEE Standards Documents

[[_DV_M4]]
IEEE Standards
documents are made available for use subject to important notices and legal
disclaimers. These notices and disclaimers, or a reference to this page (https://standards.ieee.org/ipr/disclaimers.html[]),
appear in all standards and may be found under the heading “Important Notices
and Disclaimers Concerning IEEE Standards Documents.”

==== Notice and Disclaimer of Liability Concerning the Use of IEEE Standards Documents

IEEE Standards documents are
developed within the IEEE Societies and the Standards Coordinating Committees
of the IEEE Standards Association (IEEE SA) Standards Board. IEEE develops its
standards through an accredited consensus development process, which brings
together volunteers representing varied viewpoints and interests to achieve the
final product. IEEE Standards are documents developed by volunteers with
scientific, academic, and industry-based expertise in technical working groups.
Volunteers are not necessarily members of IEEE or IEEE SA, and participate
without compensation from IEEE. While IEEE administers the process and
establishes rules to promote fairness in the consensus development process,
IEEE does not independently evaluate, test, or verify the accuracy of any of
the information or the soundness of any judgments contained in its standards.

IEEE makes no warranties or
representations concerning its standards, and expressly disclaims all
warranties, express or implied, concerning this standard, including but not
limited to the warranties of merchantability, fitness for a particular purpose
and non-infringement. In addition, IEEE
does not warrant or represent that the use of the material contained in its
standards is free from patent infringement. IEEE standards documents are
supplied “AS IS” and “WITH ALL FAULTS.”

Use of an IEEE standard is wholly
voluntary. The existence of an IEEE Standard does not imply that there are no
other ways to produce, test, measure, purchase, market, or provide other goods
and services related to the scope of the IEEE standard. Furthermore, the
viewpoint expressed at the time a standard is approved and issued is subject to
change brought about through developments in the state of the art and comments
received from users of the standard.

In publishing and
making its standards available, IEEE is not suggesting or rendering
professional or other services for, or on behalf of, any person or entity, nor
is IEEE undertaking to perform any duty owed by any other person or entity to
another. Any person utilizing any IEEE Standards document, should rely upon his
or her own independent judgment in the exercise of reasonable care in any given
circumstances or, as appropriate, seek the advice of a competent professional
in determining the appropriateness of a given IEEE standard.

IN NO EVENT SHALL IEEE
BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO: THE NEED TO PROCURE
SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
IN ANY WAY OUT OF THE PUBLICATION, USE OF, OR RELIANCE UPON ANY STANDARD, EVEN
IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE AND REGARDLESS OF WHETHER SUCH
DAMAGE WAS FORESEEABLE.

==== Translations

The IEEE consensus
development process involves the review of documents in English only. In the
event that an IEEE standard is translated, only the English version published
by IEEE is the approved IEEE standard.

==== Official statements

A statement, written
or oral, that is not processed in accordance with the IEEE SA Standards Board
Operations Manual shall not be considered or inferred to be the official
position of IEEE or any of its committees and shall not be considered to be,
nor be relied upon as, a formal position of IEEE. At lectures, symposia,
seminars, or educational courses, an individual presenting information on IEEE
standards shall make it clear that the presenter’s views should be considered
the personal views of that individual rather than the formal position of IEEE,
IEEE SA, the Standards Committee, or the Working Group.

==== Comments on standards

Comments for revision of IEEE
Standards documents are welcome from any interested party, regardless of membership
affiliation with IEEE or IEEE SA. However, *IEEE does not provide interpretations, consulting information, or advice pertaining to IEEE Standards documents*.

Suggestions for changes in
documents should be in the form of a proposed change of text, together with
appropriate supporting comments. Since IEEE standards represent a consensus of
concerned interests, it is important that any responses to comments and
questions also receive the concurrence of a balance of interests. For this
reason, IEEE and the members of its Societies and Standards Coordinating
Committees are not able to provide an instant response to comments, or
questions except in those cases where the matter has previously been addressed.
For the same reason, IEEE does not respond to interpretation requests. Any
person who would like to participate in evaluating comments or in revisions to
an IEEE standard is welcome to join the relevant IEEE working group. You can
indicate interest in a working group using the Interests tab in the Manage
Profile &#x26; Interests area of the https://development.standards.ieee.org/myproject-web/public/view.html#landing[IEEE SA myProject system].footnote:[Available at: https://development.standards.ieee.org/myproject-web/public/view.html#landing[].]
An IEEE Account is needed to access the application.

Comments on standards should be submitted using the https://standards.ieee.org/content/ieee-standards/en/about/contact/index.html[Contact Us] form.footnote:[Available at: https://standards.ieee.org/content/ieee-standards/en/about/contact/index.html[].]

==== Laws and regulations

Users of IEEE
Standards documents should consult all applicable laws and regulations.
Compliance with the provisions of any IEEE Standards document does not
constitute compliance to any applicable regulatory requirements. Implementers
of the standard are responsible for observing or referring to the applicable
regulatory requirements. IEEE does not, by the publication of its standards,
intend to urge action that is not in compliance with applicable laws, and these
documents may not be construed as doing so.

==== Data privacy

Users of IEEE Standards documents
should evaluate the standards for considerations of data privacy and data
ownership in the context of assessing and using the standards in compliance
with applicable laws and regulations.

==== Copyrights

IEEE draft and approved
standards are copyrighted by IEEE under US and international copyright
laws. They are made available by IEEE and are adopted for a wide variety of
both public and private uses. These include both use, by reference, in laws and
regulations, and use in private self-regulation, standardization, and the
promotion of engineering practices and methods. By making these documents
available for use and adoption by public authorities and private users, IEEE
does not waive any rights in copyright to the documents.

==== Photocopies

Subject to payment of the
appropriate licensing fees, IEEE will grant users a limited, non-exclusive
license to photocopy portions of any individual standard for company or
organizational internal use or individual, non-commercial use only. To arrange
for payment of licensing fees, please contact Copyright Clearance Center,
Customer Service, 222 Rosewood Drive, Danvers, MA 01923 USA; +1 978 750 8400;
\https://www.copyright.com/. Permission to photocopy portions of any individual
standard for educational classroom use can also be obtained through the
Copyright Clearance Center.

==== Updating of IEEE Standards documents

Users
of IEEE Standards documents should be aware that these documents may be
superseded at any time by the issuance of new editions or may be amended from
time to time through the issuance of amendments, corrigenda, or errata. An
official IEEE document at any point in time consists of the current edition of
the document together with any amendments, corrigenda, or errata then in
effect.

Every
IEEE standard is subjected to review at least every 10 years. When a document
is more than 10 years old and has not undergone a revision process, it is
reasonable to conclude that its contents, although still of some value, do not
wholly reflect the present state of the art. Users are cautioned to check to
determine that they have the latest edition of any IEEE standard.

In
order to determine whether a given document is the current edition and whether
it has been amended through the issuance of amendments, corrigenda, or errata,
visit https://ieeexplore.ieee.org/browse/standards/collection/ieee/[IEEE Xplore]
or https://standards.ieee.org/content/ieee-standards/en/about/contact/index.html[contact IEEE].footnote:[Available at https://ieeexplore.ieee.org/browse/standards/collection/ieee[].]
For more information about the IEEE SA or IEEE’s standards development process,
visit the IEEE SA Website.

==== Errata

Errata, if any, for all IEEE standards can be accessed on the 
https://standards.ieee.org/standard/index.html[IEEE SA Website].footnote:[Available at: https://standards.ieee.org/standard/index.html[].]
Search for standard number and year of approval to access the web page of the 
published standard. Errata links are located under the Additional Resources Details section. 
Errata are also available in https://ieeexplore.ieee.org/browse/standards/collection/ieee/[IEEE Xplore].
Users are encouraged to periodically check for errata.

==== Patents

IEEE Standards are developed in compliance with the https://standards.ieee.org/about/sasb/patcom/materials.html[IEEE SA Patent Policy].footnote:[Available at: https://standards.ieee.org/about/sasb/patcom/materials.html[].]

Attention is called to
the possibility that implementation of this standard may require use of subject
matter covered by patent rights. By publication of this standard, no position
is taken by the IEEE with respect to the existence or validity of any patent
rights in connection therewith. If a patent holder or patent applicant has
filed a statement of assurance via an Accepted Letter of Assurance, then the
statement is listed on the IEEE SA Website at https://standards.ieee.org/about/sasb/patcom/patents.html[].
Letters of Assurance may
indicate whether the Submitter is willing or unwilling to grant licenses under
patent rights without compensation or under reasonable rates, with reasonable
terms and conditions that are demonstrably free of any unfair discrimination to
applicants desiring to obtain such licenses.

Essential Patent
Claims may exist for which a Letter of Assurance has not been received. The
IEEE is not responsible for identifying Essential Patent Claims for which a
license may be required, for conducting inquiries into the legal validity or
scope of Patents Claims, or determining whether any licensing terms or
conditions provided in connection with submission of a Letter of Assurance, if
any, or in any licensing agreements are reasonable or non-discriminatory. Users
of this standard are expressly advised that determination of the validity of
any patent rights, and the risk of infringement of such rights, is entirely
their own responsibility. Further information may be obtained from the IEEE
Standards Association.

==== IMPORTANT NOTICE

IEEE Standards do not
guarantee or ensure safety, security, health, or environmental protection, or
ensure against interference with or from other devices or networks. IEEE
Standards development activities consider research and information presented to
the standards development group in developing any safety recommendations. Other
information about safety practices, changes in technology or technology implementation,
or impact by peripheral systems also may be pertinent to safety considerations
during implementation of the standard. Implementers and users of IEEE Standards
documents are responsible for determining and complying with all appropriate
safety, security, environmental, health, and interference protection practices
and all applicable laws and regulations.

[[boilerplate-participants]]
=== Participants

[[boilerplate-participants-wg]]
==== {blank}
At the time this draft {{ doctype }} was completed, the {{ working_group }} Working Group had the following membership:

++++
<membership>
++++

* {blank}
name::: &#x3c;Chair Name&#x3e;
role::: Chair
* {blank}
name::: &#x3c;Vice-chair Name&#x3e;
role::: Vice Chair
* {blank}
name::: Participant1
role::: Member
* {blank}
name::: Participant2
role::: Member
* {blank}
name::: Participant3
role::: Member
* {blank}
name::: Participant4
role::: Member
* {blank}
name::: Participant5
role::: Member
* {blank}
name::: Participant6
role::: Member
* {blank}
name::: Participant7
role::: Member
* {blank}
name::: Participant8
role::: Member
* {blank}
name::: Participant9
role::: Member

++++
</membership>
++++

[[boilerplate-participants-bg]]
==== {blank}
The following members of the {{ balloting_group_type }} {{ balloting_group }} Standards Association balloting group voted on this {{ doctype }}. Balloters may have voted for approval, disapproval, or abstention.

++++
<membership>
++++

* {blank}
name::: Balloter1
role::: Member
* {blank}
name::: Balloter2
role::: Member
* {blank}
name::: Balloter3
role::: Member
* {blank}
name::: Balloter4
role::: Member
* {blank}
name::: Balloter5
role::: Member
* {blank}
name::: Balloter6
role::: Member
* {blank}
name::: Balloter7
role::: Member
* {blank}
name::: Balloter8
role::: Member
* {blank}
name::: Balloter9
role::: Member

++++
</membership>
++++

[[boilerplate-participants-sb]]
==== {blank}

When the IEEE SA Standards Board approved this {{ doctype }} on {{ issueddate }}, it had the following membership:

++++
<membership>
++++

* {blank}
name::: &#x3c;Name&#x3e;
role::: Chair
* {blank}
name::: &#x3c;Name&#x3e;
role::: Vice Chair
* {blank}
name::: &#x3c;Name&#x3e;
role::: Past Chair
* {blank}
name::: &#x3c;Name&#x3e;
role::: Secretary
* {blank}
name::: SBMember1
role::: Member
* {blank}
name::: SBMember2
role::: Member
* {blank}
name::: SBMember3
role::: Member
* {blank}
name::: SBMember4
role::: Member
* {blank}
name::: SBMember5
role::: Member
* {blank}
name::: SBMember6
role::: Member
* {blank}
name::: SBMember7
role::: Member
* {blank}
name::: SBMember8
role::: Member
* {blank}
name::: SBMember9
role::: Member

++++
</membership>
++++

[type=emeritus_sign]
*Member Emeritus

== feedback-statement
=== {blank}
[align=left]
The Institute of Electrical and Electronics Engineers, Inc. +
3 Park Avenue, New York, NY 10016-5997, USA

=== {blank}
Copyright © {{ docyear }} by The Institute of Electrical and Electronics Engineers, Inc.

All rights reserved. Published {{ issueddate }}. Printed in the United States of America.

=== {blank}
IEEE is a registered trademark in the U.S. Patent &#x26; Trademark Office, owned by The Institute of Electrical and Electronics Engineers, Incorporated.

=== {blank}
[[_isbn_pdf_print]]
[%unnumbered]
|===
|PDF: |ISBN {{ isbn_pdf }} |{{ stdid_pdf}}
|Print: |ISBN {{ isbn_print }} |{{ stdid_print}}
|===

=== {blank}
_IEEE prohibits discrimination, harassment, and bullying._ +
_For more information, visit https://www.ieee.org/about/corporate/governance/p9-26.html[]._ +
_No part of this publication may be reproduced in any form, in an electronic retrieval system or otherwise, without the prior written permission of the publisher._

{% if docsubtype == "Amendment" or docsubtype == "Corrigendum" %}

== {blank}
[[boilerplate_front]]
[NOTE,type=boilerplate]
--
The editing instructions contained in this {{ docsubtype | downcase }} define how to merge the material contained therein into the existing base standard and its amendments to form the comprehensive standard.

The editing instructions are shown in *__bold italic__*. Four editing instructions are used: change, delete, insert, and replace. *__Change__* is used to make corrections in existing text or tables. The editing instruction specifies the location of the change and describes what is being changed by using [strike]#strikethrough# (to remove old material) and [underline]#underscore# (to add new material). *__Delete__* removes existing material. *__Insert__* adds new material without disturbing the existing material. Insertions may require renumbering. If so, renumbering instructions are given in the editing instruction. *__Replace__* is used to make changes in figures or equations by removing the existing figure or equation and replacing it with a new one. Editing instructions, change markings, and this NOTE will not be carried over into future editions because the changes will be incorporated into the base standard.
--

{% else %}
[[boilerplate_word_usage]]
== Word usage
The word _shall_ indicates mandatory requirements strictly to be followed in order to conform to the standard and from which no deviation is permitted (_shall_ equals _is required to_).footnote:[The use of the word _must_ is deprecated and cannot be used when stating mandatory requirements; _must_ is used only to describe unavoidable situations.]footnote:[The use of _will_ is deprecated and cannot be used when stating mandatory requirements; _will_ is only used in statements of fact.]

The word _should_ indicates that among several possibilities one is recommended as particularly suitable, without mentioning or excluding others; or that a certain course of action is preferred but not necessarily required (_should_ equals _is recommended that_).

The word _may_ is used to indicate a course of action permissible within the limits of the standard (_may_ equals _is permitted to_).

The word _can_ is used for statements of possibility and capability, whether material, physical, or causal (_can_ equals _is able to_).

{% endif %}

