module Metanorma
  module Ieee
    class Converter
      IEEE_LOG_MESSAGES = {
        # rubocop:disable Naming/VariableNumber
        "IEEE_2": { category: "Style",
                    error: "%s is a 4-digit number in a table column with numbers broken up in threes",
                    severity: 2 },
        "IEEE_3": { category: "Style",
                    error: "Expected title to start as: %s",
                    severity: 2 },
        "IEEE_4": { category: "Style",
                    error: "Title contains uncapitalised word other than preposition",
                    severity: 2 },
        "IEEE_5": { category: "Document Attributes",
                    error: "%s is not a recognised document type",
                    severity: 2 },
        "IEEE_6": { category: "Document Attributes",
                    error: "%s is not a recognised document subtype",
                    severity: 2 },
        "IEEE_7": { category: "Document Attributes",
                    error: "%s is not a recognised stage",
                    severity: 2 },
        "IEEE_8": { category: "Style",
                    error: "Cross-reference contains range, should be separate cross-references",
                    severity: 2 },
        "IEEE_9": { category: "Style",
                    error: "Undated reference %s should not contain specific elements",
                    severity: 2 },
        "IEEE_10": { category: "Style",
                     error: "Normative reference %s is not dated.",
                     severity: 2 },
        "IEEE_11": { category: "Style",
                     error: "Use ordered lists for lists more than two levels deep.",
                     severity: 2 },
        "IEEE_12": { category: "Style",
                     error: "Ordered lists should not be more than five levels deep.",
                     severity: 2 },
        "IEEE_13": { category: "Style",
                     error: "Image name %s is expected to be %s",
                     severity: 2 },
        #
        "IEEE_15": { category: "Style",
                     error: "More than one image in the table cell",
                     severity: 2 },
        "IEEE_16": { category: "Style",
                     error: "Editorial instruction is missing from change",
                     severity: 2 },
        "IEEE_17": { category: "Style",
                     error: "'Add' change description should start with _Insert_",
                     severity: 2 },
        "IEEE_18": { category: "Style",
                     error: "'Delete' change description should start with _Delete_",
                     severity: 2 },
        "IEEE_19": { category: "Style",
                     error: "'Modify' change description should start with _Change_ or _Replace_",
                     severity: 2 },
        "IEEE_20": { category: "Style",
                     error: "'Modify' change description for change involving figure or equation should start with _Replace_",
                     severity: 2 },
        "IEEE_21": { category: "Style",
                     error: "'Modify' change description for change not involving figure or equation should start with _Change_",
                     severity: 2 },
        "IEEE_22": { category: "Style",
                     error: "Overview clause missing",
                     severity: 2 },
        "IEEE_23": { category: "Style",
                     error: "Scope subclause missing",
                     severity: 2 },
        "IEEE_24": { category: "Style",
                     error: "Word Usage subclause missing",
                     severity: 2 },
        "IEEE_25": { category: "Style",
                     error: "Normative references missing",
                     severity: 2 },
        "IEEE_26": { category: "Style",
                     error: "Definitions missing",
                     severity: 2 },
        "IEEE_27": { category: "Style",
                     error: "(section sequencing) %s",
                     severity: 2 },
        "IEEE_28": { category: "Style",
                     error: "Document must include (references) Normative References",
                     severity: 2 },
        #
        "IEEE_30": { category: "Style",
                     error: "subclause is only child",
                     severity: 2 },
        "IEEE_31": { category: "Style",
                     error: "Bibliography must be either the first or the last document annex",
                     severity: 2 },
      }.freeze
      # rubocop:enable Naming/VariableNumber

      def log_messages
        super.merge(IEEE_LOG_MESSAGES)
      end
    end
  end
end
